import type { Trial } from './types'

/** Opening trials are fixed on the client; Trials II and III are generated by the model. */
const OPENERS: Trial[] = [
  {
    title: 'TRIAL I · LOSS',
    scenario:
      'You spend three years building something that matters to you. A project, a business, a body of work. The week before it finally goes public, a single mistake, not yours, erases most of it. The people who could fix it are gone. Nobody is watching. Nobody would blame you for walking away.',
    question: 'What do you do in the first hour?',
  },
  {
    title: 'TRIAL I · BETRAYAL',
    scenario:
      'Someone you trusted completely has been quietly working against you for months. You find out by accident, from a message they never meant you to see. They do not know you know. Tomorrow you will be in a room with them, and they will smile at you.',
    question: 'What happens in that room?',
  },
  {
    title: 'TRIAL I · THE OFFER',
    scenario:
      'A stranger offers you exactly what you have wanted for years. No catch you can see. The only condition is that you decide before you leave the room, and you cannot tell anyone how you got it.',
    question: 'What do you say, and what do you feel while you say it?',
  },
]

export function pickOpener(): Trial {
  return OPENERS[Math.floor(Math.random() * OPENERS.length)]
}
